sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
  - type: npm
    path: src/main/resources/createJsonFilesLambda/package.json
version:
  fromSource: pom.xml
linkReplacements:
  - "https://aws.amazon.com/sdkforjava/http-clients/apache-client|https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/apache/ApacheHttpClient.html"
  - "https://eclipse-ee4j.github.io/jsonb-api|https://github.com/eclipse-ee4j/jsonb-api"
build:
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: setup-java
          content:
            name: Create test_config.properties
            id: create-test-credentials
            run: echo "owner = ${{ secrets.AWS_TAG_OWNER }}" > test_config.properties
        - action: REPLACE
          stepId: build-pk-verify
          content:
            name: Run tests and build with Maven
            id: build-pk-verify
            run: mvn --batch-mode clean verify
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: "eu-central-1"
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
